/* The demo conversation. It is long on purpose: a short thread makes the map,
   the sleeping count and the search counter meaningless. Every line is about
   this product's own design, so nothing here is filler. */

export const CHAT = [
  ["you", "09:02", "Starting point: what exactly does the speed engine do to a message it puts to sleep?"],
  ["ai", "09:02", "It sets content-visibility on the element. The box keeps its size, the browser stops painting the contents, and nothing is removed from the DOM.", "What windowing is"],
  ["you", "09:03", "So the message is still in the page."],
  ["ai", "09:03", "Still in the page, still in the archive, still searchable. Only the paint is skipped."],
  ["you", "09:05", "How much stays awake either side of the viewport?"],
  ["ai", "09:05", "About a screen and a half in each direction, so scrolling never shows a blank while the browser catches up.", "The safety zone"],
  ["you", "09:06", "Show me the two properties."],
  ["ai", "09:06", "Here they are, with the intrinsic size that keeps the scrollbar honest:", "", "content-visibility: auto;\ncontain-intrinsic-size: auto 320px;"],
  ["you", "09:08", "What happens to the scrollbar when a thousand messages are windowed?"],
  ["ai", "09:08", "It stays the length it was. contain-intrinsic-size reserves each message's last measured height, so the page does not jump as things sleep and wake."],
  ["you", "09:11", "When does the engine switch itself on?"],
  ["ai", "09:11", "Past roughly 25 messages. Below that there is nothing to win and the machinery would only add risk.", "When it engages"],
  ["you", "09:13", "Does it ever scroll the page by itself?"],
  ["ai", "09:13", "No. Mounting older messages is a button you press, and it stops the moment you scroll or press a key."],
  ["you", "09:16", "Move to the archive. Where does the wrapped file key live?"],
  ["ai", "09:16", "In extension-local storage only — never in a sync store. Anything that can read it can already read the plaintext archive beside it.", "Key storage"],
  ["you", "09:18", "Justify that, briefly."],
  ["ai", "09:18", "Putting it on a sync server adds a copy an attacker can reach without touching the device, and buys nothing, because the archive itself never syncs."],
  ["you", "09:21", "What stops someone downgrading the KDF cost in the header?"],
  ["ai", "09:21", "Both layers authenticate the header, so an edited parameter breaks the tag instead of being obeyed:", "Header authentication", "if (rounds < 600000) throw new Error(\"refused\");"],
  ["you", "09:23", "And a key envelope lifted from another file?"],
  ["ai", "09:23", "Fails to open. The envelope is bound to the header it was written with, so a swap is a tag failure rather than a weaker file."],
  ["you", "09:26", "Walk me through restore when the backup is older than the current archive."],
  ["ai", "09:26", "Chats already archived are left alone; older ones the provider no longer lists come back. Nothing is overwritten and nothing is deleted.", "Restore is a merge"],
  ["you", "09:28", "What if the two disagree about a chat's title?"],
  ["ai", "09:28", "The live copy wins for titles, the archive wins for messages. A title is cosmetic; a message is the thing you came back for."],
  ["you", "09:31", "What were the two failure modes we listed for restore?"],
  ["ai", "09:31", "A file that opens weaker than it claims, and a merge that quietly loses a chat the provider has since dropped. Both are refused now.", "Two failure modes"],
  ["you", "09:34", "Deletion next. What notices that a chat is gone?"],
  ["ai", "09:34", "A once-daily full listing. Nothing else deletes, and no single failed request is treated as evidence.", "Noticing deletions"],
  ["you", "09:36", "And if that listing comes back empty because the session is signed out?"],
  ["ai", "09:36", "It refuses to act on an implausible listing. A signed-out session can never present your whole archive for deletion."],
  ["you", "09:38", "Where does the decision land?"],
  ["ai", "09:38", "With you: the chat is quarantined and flagged, and you keep it or mirror the deletion. Standing policies exist for both extremes."],
  ["you", "09:41", "The archive worker — how often does it run?"],
  ["ai", "09:41", "Roughly every three hours, shortly after the browser starts, and when you open a chat site, at most once every twenty minutes.", "The worker's clock"],
  ["you", "09:43", "Does it re-read everything each pass?"],
  ["ai", "09:43", "No. Account-scoped checkpoints mean it reads only the new gap, so a reload is not a full resync."],
  ["you", "09:45", "What does progress look like while it runs?"],
  ["ai", "09:45", "One percentage for the archive pass, rather than one bar per supported site racing the others."],
  ["you", "09:48", "Temporary chats — remind me what we decided."],
  ["ai", "09:48", "Off by default. A temporary chat is you telling that platform not to keep it, and we do not quietly overrule that.", "Temporary chats"],
  ["you", "09:50", "And when it is switched on?"],
  ["ai", "09:50", "They are archived locally, labelled temporary, with a badge on the page for as long as one is being archived. Never a silent recording."],
  ["you", "09:53", "Search. How far back does the in-chat one reach?"],
  ["ai", "09:53", "As far as the archive goes. The page holds what the site has mounted; the archived copy holds the rest.", "Search depth"],
  ["you", "09:55", "What does the counter say when they differ?"],
  ["ai", "09:55", "Both numbers: the matches on this page, and the matches further back. One number would hide the interesting half."],
  ["you", "09:58", "Give me the measured example again."],
  ["ai", "09:58", "Eight hits on the page where the conversation held two hundred and seventeen. That gap is the feature."],
  ["you", "10:01", "Timestamps. Why do some say first seen?"],
  ["ai", "10:01", "Because a browser is never told when a message was sent, except where the app keeps that in its own local state.", "The honesty rule"],
  ["you", "10:03", "So we never fake one."],
  ["ai", "10:03", "Never. A first-seen time is labelled as such, and a message that predates the install says time unknown."],
  ["you", "10:06", "The minimap. What decides a bar's colour?"],
  ["ai", "10:06", "Role and content: your messages in rose, answers pale, code blocks in the lighter pink, anything starred in gold.", "Map colours"],
  ["you", "10:08", "And the lens?"],
  ["ai", "10:08", "It is the viewport, drawn over the track. Its height is the fraction of the conversation on screen, so a long chat gives a thin lens."],
  ["you", "10:11", "Does the map wait for the page to render everything?"],
  ["ai", "10:11", "No. Where the platform hands over the whole conversation, the archived copy can fill in before the live page corrects it.", "Archive-backed map"],
  ["you", "10:14", "Adapters. What happens on a redesign?"],
  ["ai", "10:14", "Unknown structure means the extension does nothing rather than guessing. The worst case is the site's ordinary behaviour.", "Degrading safely"],
  ["you", "10:16", "How would I know it had degraded?"],
  ["ai", "10:16", "Health in the popup names which adapters are primary and which are degraded, per open tab, reading no message text."],
  ["you", "10:19", "Allowance tracking — what exactly is read?"],
  ["ai", "10:19", "Rate-limit response headers, and a response body only where the URL's own path says the response is about limits.", "What the observer reads"],
  ["you", "10:21", "Never chat traffic."],
  ["ai", "10:21", "Never chat traffic, never a stream. Requests are not altered, blocked, delayed or replayed; the page gets exactly what the network gave it."],
  ["you", "10:23", "What gets written to disk from that?"],
  ["ai", "10:23", "A redacted sample: every string over forty characters is replaced by its length, and no header bearing a token is kept."],
  ["you", "10:26", "Licensing. What does the issuer actually store?"],
  ["ai", "10:26", "A hash of the key, a device fingerprint, a hashed IP for thirty days, the trial start date, and the link between an address and a licence.", "What the issuer holds"],
  ["you", "10:28", "And if the issuer is unreachable?"],
  ["ai", "10:28", "Pro keeps working and is marked overdue. Only the issuer saying the licence is gone withdraws it — an outage never does."],
  ["you", "10:31", "Devices?"],
  ["ai", "10:31", "Five at once, released from the popup, and the oldest is freed automatically when you activate on a sixth this browser has seen before."],
  ["you", "10:34", "Context Bridge. What crosses the wire?"],
  ["ai", "10:34", "Nothing. It searches your local archive and puts the passages you tick into the prompt box you are already typing in.", "Nothing leaves"],
  ["you", "10:36", "And if the prompt box cannot be found?"],
  ["ai", "10:36", "It copies to the clipboard rather than touching a page it does not understand. A surprise insertion would be worse than a fallback."],
  ["you", "10:39", "Carrying a chat over — what is included?"],
  ["ai", "10:39", "The original ask, the messages you starred, and the last few turns. Quoted, never summarised, and nothing is sent for you.", "What carries over"],
  ["you", "10:42", "Backups. What is in the Markdown file?"],
  ["ai", "10:42", "The whole conversation with headings, lists, code fences and timestamps preserved — not the slice the page happens to hold.", "The backup file"],
  ["you", "10:44", "And JSON?"],
  ["ai", "10:44", "Role, text and timestamp per message, re-importable, for anything you want to build on top of it."],
  ["you", "10:47", "Does exporting need a licence?"],
  ["ai", "10:47", "No, and it never will. If Pro lapses or is refunded, the export still works — your archive is not held hostage."],
  ["you", "10:50", "Last one: the vector index question from last week."],
  ["ai", "10:50", "You starred that passage. It is still in the archive, and search reaches it even where this page has unloaded the message.", "The vector index"],
];

export const OLDER = [
  ["you", "08:40", "Before any of this — what is the one claim the product is built on?"],
  ["ai", "08:40", "That your conversations never leave your device. Everything else is a feature; that one is the foundation.", "The claim"],
  ["you", "08:44", "And the one server?"],
  ["ai", "08:44", "A licence issuer. It decides whether a licence is real and how many devices hold it, and it never receives conversation text."],
  ["you", "08:47", "Keep the passphrase out of storage entirely."],
  ["ai", "08:47", "It is never stored, never synced and not recoverable. The wrapped file key is what makes unattended backups possible."],
];

export const SIDEBAR = [
  { title: "Encrypted backup format", n: "1,471", q: "212", s: "9", made: "12 Jul", seen: "today" },
  { title: "Rate-limit parser", n: "486", q: "77", s: "2", made: "3 Aug", seen: "yesterday" },
  { title: "Minimap virtualisation", n: "1,120", q: "164", s: "6", made: "28 Jun", seen: "4 days ago" },
  { title: "Refund webhook", n: "—", q: "—", s: "—", made: "—", seen: "not tracked yet" },
  { title: "Extension origin bug", n: "254", q: "40", s: "1", made: "19 Aug", seen: "last week" },
];

export const ARCHIVE = [
  { when: "3 weeks ago", where: "archived elsewhere", text: "the wrapped file key never goes to a sync store — local storage only" },
  { when: "6 weeks ago", where: "archived here", text: "PBKDF2 at 1,000,000 rounds wraps a random file key; the body is AES-256-GCM" },
  { when: "2 months ago", where: "archived elsewhere", text: "vector index: keep it out of the hot path, rebuild lazily on first search" },
];

export const MESSAGES = CHAT.map(([r, t, x, h, code]) => ({ r, t, x, h, code }));
export const OLDER_MESSAGES = OLDER.map(([r, t, x, h]) => ({ r, t, x, h }));
